pool:
  vmImage: windows-2019

variables:
- group: Xamarin NuGetized

resources:
  repositories:
  - repository: templates
    type: github
    name: xamarin/yaml-templates
    ref: refs/heads/master
    endpoint: xamarin

steps:

- checkout: self
  clean: true

- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    useGlobalJson: true

- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: 2.1.x

- task: MSBuild@1
  displayName: Restore
  inputs:
    solution: build.proj
    msbuildArguments: /t:Restore /bl:"$(Build.ArtifactStagingDirectory)\restore.binlog"

- task: MSBuild@1
  displayName: Build
  inputs:
    solution: build.proj
    msbuildArguments: /t:Build /p:Out="$(Build.ArtifactStagingDirectory)" /bl:"$(Build.ArtifactStagingDirectory)\build.binlog"

- task: VSTest@2
  displayName: Test
  inputs:
    testAssemblyVer2: |-
      **\*.Tests.dll
      !**\xunit*.dll
    codeCoverageEnabled: 'true'
    publishRunAttachments: 'true'

- template: sleet/v1.yml@templates
  parameters:
    connectionString: $(SLEET_FEED_CONNECTIONSTRING)
    container: xvs
    packages: $(Build.ArtifactStagingDirectory)

- task: PublishBuildArtifacts@1
  displayName: Publish
  condition: always()
  inputs:
    PathtoPublish: $(Build.ArtifactStagingDirectory)
    ArtifactName: output
    ArtifactType: Container
