pool:
  vmImage: windows-2019

variables:
- group: Xamarin NuGetized

steps:

- checkout: self
  clean: true

- task: DotNetCoreInstaller@0
  displayName: 'Use .NET Core sdk 2.1.500'
  inputs:
    version: 2.1.500
  
- task: MSBuild@1
  displayName: Restore
  inputs:
    solution: build.proj
    msbuildArguments: /t:Restore /bl:"$(Build.ArtifactStagingDirectory)\restore.binlog"

- task: MSBuild@1
  displayName: Build
  inputs:
    solution: build.proj
    msbuildArguments: /t:Build /p:Out="$(Build.ArtifactStagingDirectory)" /bl:"$(Build.ArtifactStagingDirectory)\build.binlog"

- task: VSTest@2
  displayName: Test
  inputs:
    testAssemblyVer2: |-
      **\*.Tests.dll
      !**\xunit*.dll
    codeCoverageEnabled: 'true'
    publishRunAttachments: 'true'

- task: MSBuild@1
  displayName: Push
  inputs:
    solution: build.proj
    msbuildArguments: /t:Publish /p:Out="$(Build.ArtifactStagingDirectory)" /p:StorageAccessKey=$(StorageAccessKey) /p:StorageAccount=nugetized /p:StorageContainer=xvs /bl:"$(Build.ArtifactStagingDirectory)\push.binlog"

- task: PublishBuildArtifacts@1
  displayName: Publish
  condition: always()
  inputs:
    PathtoPublish: $(Build.ArtifactStagingDirectory)
    ArtifactName: output
    ArtifactType: Container
